apiVersion: actions.github.com/v1alpha1
kind: RunnerScaleSet
metadata:
  name: arl-windows
  namespace: arc-systems
spec:
  githubConfigUrl: https://github.com/TWOJA_ORG
  githubConfigSecret:
    github_token: github-pat

  minRunners: 0
  maxRunners: 1

  template:
    spec:
      nodeSelector:
        platform: ARL
        kubernetes.io/os: windows

      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "runner"
          effect: "NoSchedule"

      containers:
        - name: runner
          image: ghcr.io/TWOJA_ORG/runner-windows:latest
          